branch-defaults:
  main:
    environment: null
  master:
    environment: null
    group_suffix: null
global:
  application_name: django-tutorial
  branch: main
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: blog
  sc: git
  workspace_type: Application
