# Generated by Django 3.2.4 on 2022-02-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20220220_1334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myuser',
        ),
    ]
