# Generated by Django 3.2.4 on 2021-09-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(default='uncategorized', max_length=255),
        ),
    ]
