# Generated by Django 3.2.4 on 2021-10-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypost', '0004_auto_20210929_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Category',
            field=models.CharField(default='uncategorized', max_length=255),
        ),
    ]
