# Generated by Django 3.2.4 on 2022-02-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypost', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
