# Generated by Django 3.2.4 on 2022-04-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypost', '0010_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='Category',
            field=models.CharField(max_length=255),
        ),
    ]
