# Generated by Django 3.2.4 on 2022-04-06 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypost', '0012_comment_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_name',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='mypost.post'),
        ),
    ]
