# Generated by Django 3.2.4 on 2022-05-29 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypost', '0015_auto_20220408_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
